// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "97ba9a30-6cd8-4c59-948b-6778254ef920";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onMaxNumOfPplChange();
void onNumOfPplChange();
void onBeaconKillSwitchChange();
void onNumOfPplRstChange();

float iotBusvoltage;
float iotCurrent_mA;
float iotLoadvoltage;
float iotPower_mW;
float iotShuntvoltage;
int maxNumOfPpl;
int numOfPpl;
bool beacon;
bool beaconKillSwitch;
bool numOfPplRst;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(iotBusvoltage, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(iotCurrent_mA, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(iotLoadvoltage, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(iotPower_mW, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(iotShuntvoltage, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(maxNumOfPpl, READWRITE, ON_CHANGE, onMaxNumOfPplChange);
  ArduinoCloud.addProperty(numOfPpl, READWRITE, ON_CHANGE, onNumOfPplChange, 1);
  ArduinoCloud.addProperty(beacon, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(beaconKillSwitch, READWRITE, ON_CHANGE, onBeaconKillSwitchChange);
  ArduinoCloud.addProperty(numOfPplRst, READWRITE, ON_CHANGE, onNumOfPplRstChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
